services:
  rocky8build:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL8
        image: php-8.2
  rocky9build:
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL9
        image: php-8.2
  stream9build:
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $OS9
        image: php-8.2

volumes:
  rpm8rocky:
    name: rpm8rocky
  rpm9rocky:
    name: rpm9rocky
  rpm9stream:
    name: rpm9stream
