version: "3"
services:
  rocky8build:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL8
  stream9build:
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $OS9

volumes:
  rpm8rocky:
    name: rpm8rocky
  rpm9stream:
    name: rpm9stream